const taskDb = require('./taskDb.cjs');

const DAY_MS = 24 * 60 * 60 * 1000;
const now = Date.now();
const startOfToday = new Date();
startOfToday.setHours(0, 0, 0, 0);
const today = startOfToday.getTime();

function dateOffset(days) {
    return today + days * DAY_MS;
}

function ymd(timestamp) {
    return new Date(timestamp).toISOString().slice(0, 10);
}

function task(overrides) {
    const createdAt = overrides.created_at || dateOffset(-10);
    const updatedAt = overrides.updated_at || createdAt;
    return {
        id: overrides.id,
        title: overrides.title,
        period: overrides.period || 'daily',
        kanban_col: overrides.kanban_col || 'todo',
        priority: overrides.priority || 'p2',
        is_focused: Boolean(overrides.is_focused),
        memo: overrides.memo || '',
        is_review: Boolean(overrides.is_review),
        project: overrides.project || null,
        parent_id: overrides.parent_id || null,
        plan_date: overrides.plan_date ?? dateOffset(0),
        due_date: overrides.due_date ?? dateOffset(1),
        completed_at: overrides.completed_at || null,
        deleted_at: overrides.deleted_at || null,
        sort_order: overrides.sort_order || updatedAt,
        planned_pomodoros: overrides.planned_pomodoros ?? 0,
        actual_pomodoros: overrides.actual_pomodoros ?? 0,
        planned_amount: overrides.planned_amount ?? 0,
        completed_amount: overrides.completed_amount ?? 0,
        unit: overrides.unit || null,
        tags: overrides.tags || ['测试种子'],
        creator_agent: overrides.creator_agent || 'SeedAgent',
        knowledge_tags: overrides.knowledge_tags || [],
        external_urls: overrides.external_urls || [],
        review_info: overrides.review_info || null,
        review_history: overrides.review_history || [],
        ai_meta_json: overrides.ai_meta_json || null,
        color: overrides.color || null,
        created_at: createdAt,
        updated_at: updatedAt
    };
}

function doneAt(days, hour = 20) {
    return dateOffset(days) + hour * 60 * 60 * 1000;
}

function createSeedTasks() {
    return [
        task({
            id: 'epic-english-90-days',
            title: '长期目标：90 天英语听说读写提升',
            period: 'long_term',
            kanban_col: 'in_progress',
            priority: 'p0',
            plan_date: dateOffset(-14),
            due_date: dateOffset(76),
            sort_order: 100,
            planned_pomodoros: 120,
            planned_amount: 90,
            unit: '天',
            tags: ['长期', '英语', '学习', '测试种子'],
            color: '#3B82F6',
            memo: '覆盖三个月长期目标：下挂短期周目标，再下挂今日任务；实际番茄钟和完成量应由子任务自动汇总。',
            created_at: dateOffset(-14),
            updated_at: dateOffset(0)
        }),
        task({
            id: 'story-english-week-listening',
            title: '短期目标：本周完成英语听力基础训练',
            period: 'short_term',
            kanban_col: 'in_progress',
            priority: 'p0',
            parent_id: 'epic-english-90-days',
            project: 'epic-english-90-days',
            plan_date: dateOffset(-2),
            due_date: dateOffset(5),
            sort_order: 200,
            planned_pomodoros: 12,
            planned_amount: 7,
            unit: '天',
            tags: ['短期', '英语听力', '测试种子'],
            color: '#2563EB',
            memo: '父级短期任务，不手填实际量；实际量来自下方 daily 子任务。',
            created_at: dateOffset(-3),
            updated_at: dateOffset(0)
        }),
        task({
            id: 'daily-english-listening-shadowing-done',
            title: '今日任务：精听 TED 片段并跟读 20 分钟',
            period: 'daily',
            kanban_col: 'done',
            priority: 'p0',
            is_focused: false,
            parent_id: 'story-english-week-listening',
            project: 'story-english-week-listening',
            plan_date: dateOffset(0),
            due_date: dateOffset(0),
            completed_at: doneAt(0, 9),
            sort_order: 300,
            planned_pomodoros: 2,
            actual_pomodoros: 2,
            planned_amount: 20,
            completed_amount: 20,
            unit: '分钟',
            tags: ['今日', '英语听力', '已完成', '测试种子'],
            color: '#10B981',
            created_at: dateOffset(-1),
            updated_at: doneAt(0, 9)
        }),
        task({
            id: 'daily-english-vocab-focus',
            title: '今日任务：背诵核心词汇 40 个',
            period: 'daily',
            kanban_col: 'in_progress',
            priority: 'p1',
            is_focused: true,
            parent_id: 'story-english-week-listening',
            project: 'story-english-week-listening',
            plan_date: dateOffset(0),
            due_date: dateOffset(0),
            sort_order: 310,
            planned_pomodoros: 3,
            actual_pomodoros: 0,
            planned_amount: 40,
            completed_amount: 0,
            unit: '词',
            tags: ['今日', '英语词汇', '专注', '测试种子'],
            color: '#4A9D9A',
            created_at: dateOffset(0),
            updated_at: now
        }),
        task({
            id: 'daily-english-reading-todo',
            title: '今日任务：阅读英语短文并摘录 5 句',
            period: 'daily',
            kanban_col: 'todo',
            priority: 'p2',
            parent_id: 'story-english-week-listening',
            project: 'story-english-week-listening',
            plan_date: dateOffset(0),
            due_date: dateOffset(1),
            sort_order: 320,
            planned_pomodoros: 2,
            actual_pomodoros: 0,
            planned_amount: 5,
            completed_amount: 0,
            unit: '句',
            tags: ['今日', '英语阅读', '测试种子'],
            created_at: dateOffset(0),
            updated_at: dateOffset(0)
        }),
        task({
            id: 'story-english-week-speaking',
            title: '短期目标：本周完成 3 次口语输出',
            period: 'short_term',
            kanban_col: 'todo',
            priority: 'p1',
            parent_id: 'epic-english-90-days',
            project: 'epic-english-90-days',
            plan_date: dateOffset(1),
            due_date: dateOffset(7),
            sort_order: 210,
            planned_pomodoros: 9,
            planned_amount: 3,
            unit: '次',
            tags: ['短期', '英语口语', '测试种子'],
            color: '#60A5FA',
            created_at: dateOffset(-1),
            updated_at: dateOffset(0)
        }),
        task({
            id: 'daily-english-speaking-overdue',
            title: '逾期任务：录制 2 分钟英语自我介绍',
            period: 'daily',
            kanban_col: 'todo',
            priority: 'p1',
            parent_id: 'story-english-week-speaking',
            project: 'story-english-week-speaking',
            plan_date: dateOffset(-2),
            due_date: dateOffset(-1),
            sort_order: 330,
            planned_pomodoros: 1,
            actual_pomodoros: 0,
            planned_amount: 1,
            completed_amount: 0,
            unit: '段',
            tags: ['逾期', '英语口语', '测试种子'],
            color: '#F59E0B',
            created_at: dateOffset(-3),
            updated_at: dateOffset(-1)
        }),
        task({
            id: 'epic-vcp-platform-120-days',
            title: '长期目标：4 个月打磨 TaskOrbit 任务中枢',
            period: 'long_term',
            kanban_col: 'in_progress',
            priority: 'p1',
            plan_date: dateOffset(-20),
            due_date: dateOffset(100),
            sort_order: 120,
            planned_pomodoros: 160,
            planned_amount: 12,
            unit: '模块',
            tags: ['长期', '产品', '开发', '测试种子'],
            color: '#3E3A36',
            memo: '覆盖四个月长期目标、甘特图项目节点、短期迭代与今日开发任务。',
            created_at: dateOffset(-20),
            updated_at: dateOffset(0)
        }),
        task({
            id: 'story-vcp-sync-and-db',
            title: '短期目标：完成任务同步与数据库安全闭环',
            period: 'short_term',
            kanban_col: 'in_progress',
            priority: 'p0',
            parent_id: 'epic-vcp-platform-120-days',
            project: 'epic-vcp-platform-120-days',
            plan_date: dateOffset(-4),
            due_date: dateOffset(3),
            sort_order: 220,
            planned_pomodoros: 14,
            planned_amount: 5,
            unit: '接口',
            tags: ['短期', '同步', '数据库', '测试种子'],
            color: '#F43F5E',
            created_at: dateOffset(-6),
            updated_at: dateOffset(0)
        }),
        task({
            id: 'daily-vcp-fix-upsert-done',
            title: '今日任务：修复空标题导致 upsert 失败',
            period: 'daily',
            kanban_col: 'done',
            priority: 'p0',
            parent_id: 'story-vcp-sync-and-db',
            project: 'story-vcp-sync-and-db',
            plan_date: dateOffset(-1),
            due_date: dateOffset(0),
            completed_at: doneAt(0, 11),
            sort_order: 340,
            planned_pomodoros: 2,
            actual_pomodoros: 2,
            planned_amount: 1,
            completed_amount: 1,
            unit: '缺陷',
            tags: ['今日', 'Bugfix', '已完成', '测试种子'],
            color: '#EF4444',
            created_at: dateOffset(-1),
            updated_at: doneAt(0, 11)
        }),
        task({
            id: 'daily-vcp-aggregate-metrics',
            title: '今日任务：验证父级任务自动汇总实际量',
            period: 'daily',
            kanban_col: 'done',
            priority: 'p1',
            parent_id: 'story-vcp-sync-and-db',
            project: 'story-vcp-sync-and-db',
            plan_date: dateOffset(0),
            due_date: dateOffset(0),
            completed_at: doneAt(0, 14),
            sort_order: 350,
            planned_pomodoros: 3,
            actual_pomodoros: 3,
            planned_amount: 2,
            completed_amount: 2,
            unit: '用例',
            tags: ['今日', '统计', '已完成', '测试种子'],
            color: '#8B5CF6',
            created_at: dateOffset(0),
            updated_at: doneAt(0, 14)
        }),
        task({
            id: 'daily-vcp-drawer-readonly',
            title: '今日任务：检查详情抽屉实际量只读',
            period: 'daily',
            kanban_col: 'todo',
            priority: 'p2',
            parent_id: 'story-vcp-sync-and-db',
            project: 'story-vcp-sync-and-db',
            plan_date: dateOffset(0),
            due_date: dateOffset(2),
            sort_order: 360,
            planned_pomodoros: 2,
            actual_pomodoros: 0,
            planned_amount: 1,
            completed_amount: 0,
            unit: '页面',
            tags: ['今日', 'UI', '测试种子'],
            created_at: dateOffset(0),
            updated_at: dateOffset(0)
        }),
        task({
            id: 'epic-review-knowledge-base',
            title: '长期目标：知识库与艾宾浩斯复习体系',
            period: 'long_term',
            kanban_col: 'todo',
            priority: 'p2',
            plan_date: dateOffset(-7),
            due_date: dateOffset(83),
            sort_order: 140,
            planned_pomodoros: 80,
            planned_amount: 100,
            unit: '%',
            tags: ['长期', '复习', '知识库', '测试种子'],
            color: '#8B5CF6',
            created_at: dateOffset(-7),
            updated_at: dateOffset(-1)
        }),
        task({
            id: 'story-review-vue-reactivity',
            title: '短期目标：复习 Vue 响应式与组合式 API',
            period: 'short_term',
            kanban_col: 'in_progress',
            priority: 'p1',
            parent_id: 'epic-review-knowledge-base',
            project: 'epic-review-knowledge-base',
            plan_date: dateOffset(-1),
            due_date: dateOffset(6),
            sort_order: 230,
            planned_pomodoros: 8,
            planned_amount: 4,
            unit: '主题',
            tags: ['短期', '复习', 'Vue', '测试种子'],
            color: '#A855F7',
            created_at: dateOffset(-3),
            updated_at: dateOffset(0)
        }),
        task({
            id: 'daily-review-vue-reactivity-due',
            title: '复习任务：Vue 响应式原理今天到期',
            period: 'daily',
            kanban_col: 'done',
            priority: 'p2',
            parent_id: 'story-review-vue-reactivity',
            project: 'story-review-vue-reactivity',
            plan_date: dateOffset(-2),
            due_date: dateOffset(-1),
            completed_at: doneAt(-1, 19),
            sort_order: 370,
            planned_pomodoros: 2,
            actual_pomodoros: 2,
            planned_amount: 25,
            completed_amount: 25,
            unit: '页',
            is_review: true,
            knowledge_tags: ['Vue3', '响应式', 'Proxy'],
            external_urls: ['https://vuejs.org/guide/extras/reactivity-in-depth.html'],
            review_info: { next_review_date: ymd(dateOffset(0)), stage: 1, completed: false },
            review_history: [
                { reviewed_at: doneAt(-1, 19), remembered: true, stage_before: 0, stage_after: 1, next_review_date: ymd(dateOffset(0)) }
            ],
            tags: ['复习到期', '已完成', '测试种子'],
            color: '#4A9D9A',
            created_at: dateOffset(-4),
            updated_at: doneAt(-1, 19)
        }),
        task({
            id: 'daily-review-sqlite-future',
            title: '复习任务：SQLite WAL 笔记五天后复习',
            period: 'daily',
            kanban_col: 'done',
            priority: 'p3',
            parent_id: 'story-review-vue-reactivity',
            project: 'story-review-vue-reactivity',
            plan_date: dateOffset(-5),
            due_date: dateOffset(-4),
            completed_at: doneAt(-4, 18),
            sort_order: 380,
            planned_pomodoros: 1,
            actual_pomodoros: 1,
            planned_amount: 1,
            completed_amount: 1,
            unit: '篇',
            is_review: true,
            knowledge_tags: ['SQLite', 'WAL', '本地优先'],
            external_urls: ['https://sqlite.org/wal.html'],
            review_info: { next_review_date: ymd(dateOffset(5)), stage: 2, completed: false },
            review_history: [
                { reviewed_at: doneAt(-4, 18), remembered: true, stage_before: 1, stage_after: 2, next_review_date: ymd(dateOffset(5)) }
            ],
            tags: ['未来复习', '测试种子'],
            color: '#6366F1',
            created_at: dateOffset(-6),
            updated_at: doneAt(-4, 18)
        }),
        task({
            id: 'daily-review-completed-closed',
            title: '复习任务：已完成所有阶段的闭环样本',
            period: 'daily',
            kanban_col: 'done',
            priority: 'p3',
            parent_id: 'story-review-vue-reactivity',
            project: 'story-review-vue-reactivity',
            plan_date: dateOffset(-30),
            due_date: dateOffset(-29),
            completed_at: doneAt(-29, 21),
            sort_order: 390,
            planned_pomodoros: 1,
            actual_pomodoros: 1,
            planned_amount: 1,
            completed_amount: 1,
            unit: '卡片',
            is_review: false,
            knowledge_tags: ['已掌握', '闭环'],
            review_info: { next_review_date: '', stage: 6, completed: true },
            review_history: [
                { reviewed_at: doneAt(-29, 21), remembered: true, stage_before: 5, stage_after: 6, next_review_date: '' }
            ],
            tags: ['复习闭环', '测试种子'],
            color: '#22C55E',
            created_at: dateOffset(-40),
            updated_at: doneAt(-29, 21)
        }),
        task({
            id: 'routine-daily-review-10min',
            title: '常驻习惯：每日复盘 10 分钟',
            period: 'routine',
            kanban_col: 'todo',
            priority: 'p2',
            plan_date: dateOffset(0),
            due_date: null,
            sort_order: 500,
            planned_pomodoros: 1,
            actual_pomodoros: 0,
            planned_amount: 10,
            completed_amount: 0,
            unit: '分钟',
            tags: ['常驻', '习惯', '复盘', '测试种子'],
            color: '#81C784',
            created_at: dateOffset(-12),
            updated_at: dateOffset(0)
        }),
        task({
            id: 'routine-english-checkin',
            title: '常驻习惯：英语每日打卡',
            period: 'routine',
            kanban_col: 'done',
            priority: 'p2',
            plan_date: dateOffset(0),
            due_date: null,
            completed_at: doneAt(0, 8),
            sort_order: 510,
            planned_pomodoros: 1,
            actual_pomodoros: 1,
            planned_amount: 1,
            completed_amount: 1,
            unit: '次',
            tags: ['常驻', '英语', '已完成', '测试种子'],
            color: '#16A34A',
            created_at: dateOffset(-20),
            updated_at: doneAt(0, 8)
        }),
        task({
            id: 'daily-unscheduled-inbox-like',
            title: '未排期任务：等待拆解的灵感',
            period: 'daily',
            kanban_col: 'todo',
            priority: 'p3',
            plan_date: null,
            due_date: null,
            sort_order: 600,
            planned_pomodoros: 0,
            actual_pomodoros: 0,
            planned_amount: 0,
            completed_amount: 0,
            unit: null,
            tags: ['未排期', '收集箱', '测试种子'],
            memo: '覆盖无计划日/无截止日任务，应进入未排期或总览过滤场景。',
            created_at: dateOffset(0),
            updated_at: dateOffset(0)
        }),
        task({
            id: 'daily-empty-title-fallback',
            title: '未命名任务',
            period: 'daily',
            kanban_col: 'todo',
            priority: 'p3',
            plan_date: dateOffset(2),
            due_date: dateOffset(3),
            sort_order: 610,
            planned_pomodoros: 1,
            actual_pomodoros: 0,
            planned_amount: 1,
            completed_amount: 0,
            unit: '项',
            tags: ['标题兜底', '测试种子'],
            memo: '覆盖未命名任务在排期中心中的过滤/兜底展示。',
            created_at: dateOffset(0),
            updated_at: dateOffset(0)
        }),
        task({
            id: 'daily-soft-deleted-restore',
            title: '已软删除任务：回收站恢复验证',
            period: 'daily',
            kanban_col: 'todo',
            priority: 'p3',
            plan_date: dateOffset(-2),
            due_date: dateOffset(1),
            deleted_at: dateOffset(-1),
            sort_order: 900,
            planned_pomodoros: 1,
            actual_pomodoros: 0,
            planned_amount: 1,
            completed_amount: 0,
            unit: '条',
            tags: ['软删除', '回收站', '测试种子'],
            created_at: dateOffset(-4),
            updated_at: dateOffset(-1)
        }),
        task({
            id: 'daily-completed-yesterday-trend',
            title: '昨日完成任务：效能趋势样本',
            period: 'daily',
            kanban_col: 'done',
            priority: 'p2',
            plan_date: dateOffset(-1),
            due_date: dateOffset(-1),
            completed_at: doneAt(-1, 20),
            sort_order: 620,
            planned_pomodoros: 2,
            actual_pomodoros: 2,
            planned_amount: 2,
            completed_amount: 2,
            unit: '项',
            tags: ['统计', '趋势', '测试种子'],
            created_at: dateOffset(-2),
            updated_at: doneAt(-1, 20)
        })
    ];
}

async function main() {
    const tasks = createSeedTasks();
    const saved = await taskDb.replaceAllTasks(tasks);
    console.log(`[seed-test-data] 已清空数据库并写入 ${saved.length} 条覆盖测试用例的种子任务。`);
    console.log('[seed-test-data] 覆盖范围：长期目标、短期目标、今日任务、常驻习惯、复习任务、父子层级、逾期、未排期、软删除、标题兜底、趋势统计、实际量自动统计。');
    console.log(`[seed-test-data] 数据库: ${taskDb.dbPath}`);
}

main().catch(error => {
    console.error('[seed-test-data] 写入失败:', error);
    process.exitCode = 1;
});
